name: Analyze
on: [ push ]
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install Dependencies via Composer
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: PHPStan
        run: vendor/bin/phpstan --memory-limit=1024M --error-format=github
